### ISSUE TITLE
npm run koa的时候报错

### ISSUE THREAD

**Issue by magicly** [17koa/koa-generator#30]
执行npm start和npm run pm2都正常运行， 但是执行npm run koa的时候报错如下， 很奇怪哎：

> koa-test@0.1.0 koa /Users/magicly/development/koa-test
> runkoa bin/www

bin/www
3babel presets path = /Users/magicly/development/koa-test/node_modules/runkoa/node_modules/
/Users/magicly/development/koa-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "/Users/magicly/development/koa-test/node_modules/runkoa/node_modules/babel-plugin-add-module-exports" specified in "base" at 0, attempted to resolve relative to "/Users/magicly/development/koa-test/bin"
    at /Users/magicly/development/koa-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/magicly/development/koa-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/magicly/development/koa-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/magicly/development/koa-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at compile (/Users/magicly/development/koa-test/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/magicly/development/koa-test/node_modules/babel-register/lib/node.js:148:14)
    at Object.require.extensions.(anonymous function) [as .js](/Users/magicly/development/koa-test/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/magicly/.nvm/versions/node/v6.2.1/bin/node" "/Users/magicly/.nvm/versions/node/v6.2.1/bin/npm" "run" "koa"

**Comment by sinalvee** [comment]
#25

**Comment by jerossh** [comment]
我执行 npm start 就报错了，mac最新系统。。。win好像根本就不支持，最后还是自己手动配置了 babel，我发现是 runkoa 依赖有问题。
