### ISSUE TITLE
npm start 就报错， runkoa 模块依赖的有问题

### ISSUE THREAD

**Issue by jerossh** [17koa/koa-generator#35]
```
/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-core/6.18.2/babel-core/lib/transformation/file/options/option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/1.5.6/runkoa/babel-plugin-add-module-exports" specified in "base" at 0, attempted to resolve relative to "/Users/Jon_shen/Documents/workpace/mingpian-koa/bin"
    at /Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-core/6.18.2/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-core/6.18.2/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-core/6.18.2/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-core/6.18.2/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-register/6.18.0/babel-register/lib/node.js:103:45)
    at loader (/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-register/6.18.0/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Jon_shen/Documents/workpace/mingpian-koa/node_modules/.npminstall/babel-register/6.18.0/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
自己在 run 文件中受冻配置了 babel就正常了

**Comment by unknown-coder** [comment]
请问你是怎么配置的呢？我也报错了
